### ISSUE TITLE
[OperaGxTheme] - weird flashing when hovering over servers / folders sometimes

### ISSUE THREAD

**Issue by VerstreuteSeele** [Tomrdh/discord-addons#10]
Hey there!

really love your theme!

but I got one small issue. sometimes when hovering over a folder icon (when its open) or over the small gaps between servers the entire folder flashes. I guess its weird to explain so best I make a video and attach it. 
![iSPzjwD3Ma](https://user-images.githubusercontent.com/55334727/133417926-fb6c9ae7-629a-40ca-bdaf-014fe54ed8ca.gif)

got any fix for this?

**Comment by u2147483647** [comment]
Hi, I am aware about that issue between Opera GX Gaming theme and Serverlist at bottom, currently I have no idea about how to fix it, but when I'll get some time, I'll look more into it. It's added to my to-do list in the support server that you can check if you want, also thanks for reporting

**Comment by u2147483647** [comment]
Hi again, can you list which themes are enabled in your Discord? I weirdly no longer have this issue 🤔

**Comment by VerstreuteSeele** [comment]
sure. so after some investigating I figured out its the "Horizontal Serverlist" mini-theme that causes this. i never seen that issue before so its certainly not the theme on its own but rather something conflicting with your theme. heres the css for it: https://discordstyles.github.io/HorizontalServerList/dist/HorizontalServerList.css

**Comment by VerstreuteSeele** [comment]
the theme literally just imports that and does nothing else so.. yeah

**Comment by u2147483647** [comment]
Thanks, that was what I guessed. Opera GX Gaming theme is currently more compatible with [Serverlist at bottom](https://github.com/Tomrdh/discord-addons/tree/master/download-themes-here/ServerlistAtBottom) directly from this repo, the only big difference is that the server list will be at the bottom instead of the top. I'll try making changes to fix at least that flashing issue, but I have no idea about how to fix border lines when servers are at the top, without breaking them when they're at the bottom.

**Comment by u2147483647** [comment]
I made some changes, close the issue if you see that it has been fixed, otherwise comment if you still have a problem.

**Comment by VerstreuteSeele** [comment]
true legend
